version: '3.8'

include:
    - proxy.yaml

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.python
    container_name: reverse-proxy
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=172.20.0.10                 
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    depends_on:
      - database
    networks:
      app-network:
        ipv4_address: 172.20.0.5            
    restart: unless-stopped

  database:
    image: mysql:8
    container_name: database_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      app-network:
        ipv4_address: 172.20.0.10           
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24  
          gateway: 172.20.0.1 
