version: "3.8"
include:
   - proxy.yaml
services:
   app:
    build: . # Собираем образ из Dockerfile в текущей директории
    container_name: reverse-proxy
    environment:
      - NODE_ENV=production
    depends_on:
      - database # Указываем зависимость от сервиса 'database'
  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
