version: "3.8"
include:
   - proxy.yaml
services:
   app:
    build: . # Собираем образ из Dockerfile в текущей директории
    container_name: my-app
    environment:
      - NODE_ENV=production
    depends_on:
      - database # Указываем зависимость от сервиса 'database'
  database:
    image: mariadb:latest
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
