FROM python:3.12-slim

LABEL maintainer="alehandromunis@gmail.com"
LABEL description="Reverse-proxy по ДЗ от Нетологии"



# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 
